PAVE-92: Merge story/PAVE-92/take-home-assignment-docs to master
Accredifysg/Dev-Interview pull request #3
Opened 2021-11-11 11:42 UTC by Abdulhakimsg

Pull request created in: https://accredify.atlassian.net/browse/PAVE-92 by the Git Integration for Jira app.

2021-11-11 12:20 UTC, derrickleemy requested changes

2021-11-11 12:20 UTC, derrickleemy commented on README.md
> +>For current open positions, please see [here](https://www.linkedin.com/company/accredify/jobs/)
https://accredify-talent.freshteam.com/jobs

2021-11-12 02:15 UTC, Abdulhakimsg commented
ok have made a commit to change the job link

2021-11-12 06:35 UTC, derrickleemy approved these changes

2021-11-12 06:35 UTC, derrickleemy commented
@Abdulhakimsg Looks good, will approve. Can you walk me through the technical assignment for frontend? Please schedule a time with me

2021-11-15 05:56 UTC, merged